### ISSUE TITLE
[UI] Adjusting Grid Size/Cell Area

### ISSUE THREAD

**Issue by arkaray** [sharmaeklavya2/packing-game#8]
Will look good on smaller devices etc. More importantly, should help with #7.

**Comment by sharmaeklavya2** [comment]
It would be good to have this, but it doesn't seem very important, since the user can just zoom in, right?

There's the issue of pixellation, though, if we only rely on zooming by user-agent and the user zooms in too much.

**Comment by sharmaeklavya2** [comment]
There's the issue of pixellation, though, if we only rely on zooming by user-agent.

**Comment by sharmaeklavya2** [comment]
There's a query parameter `scaleFactor` that can be used to set the grid cell size in pixels at the beginning of the game. For example https://sharmaeklavya2.github.io/packing-game/?srctype=gen&src=bp1&scaleFactor=10

**Comment by sharmaeklavya2** [comment]
There's a function ~`resizeGame`~ `restartGame` that can be called from the developer console. It re-initializes the game, though, so all progress would be lost.

**Comment by sharmaeklavya2** [comment]
Possible implementation strategies:

1. somehow zoom the entire `arena.div` or `arena-wrapper.div`. I tried `transform: scale(1.5)` on `arena-wrapper.div`, and it does scale all items proportionally, but the game becomes unusable because I think position calculations don't work correctly after scaling. Also, `transform.scale` increases thickness of borders and grid-lines, which is bad in my opinion.

2. iterate over everything and update position and dimensions.

**Comment by arkaray** [comment]
The issue was actually meant to be two-fold:

1. ~~How large the game appears~~
2. How many cells there are in the bins (8x8 currently) and the storage area(ax8).

The first part you have addressed for now. Though more work can be done.
Second part is the more important part. 

Basically I wanted a larger bin, and possible variation in item size and number.

The title was probably a bit misleading and also possibly the issue is combining two problems into one.

**Comment by sharmaeklavya2** [comment]
Choosing dimensions of the bin in terms of number of cells is already implemented in `bp1`, and can be controlled using querystring parameters `xLen` and `yLen`. See the example in #2.
